function createfigure(YMatrix1)
%CREATEFIGURE(YMATRIX1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 26-Jun-2015 23:16:29

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'XTickLabel',['0  ';'20 ';'40 ';'60 ';'80 ';'100'],...
    'XTick',[0 20 40 60 80 100],...
    'GridAlpha',0.1,...
    'TickLength',[0.01 0.6],...
    'FontSize',20);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 72]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-0.3 1.5]);
grid(axes1,'on');
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot(YMatrix1,'LineWidth',2);

% Create xlabel
xlabel('Feature index');

% Create ylabel
ylabel(' ''out-of-bag'' feature importance');

