
trainingdata(:,1) = [DETERMINE_ejectionFractions' ; MESA_ejectionFractions'];
%modes of variation
% trainingdata(:,2:6) = [DETERMINE_sys_myo_b(:,1:5) ; MESA_sys_myo_b(:,1:5)]; %from the PDM
% trainingdata(:,7:11) = [DETERMINE_dia_myo_b(:,1:5) ; MESA_dia_myo_b(:,1:5)];
trainingdata(:,2:16) = [DETERMINE_dia_sys_myo_b(:,1:15) ; MESA_dia_sys_myo_b(:,1:15)];
%sphericity measure
trainingdata(:,17) = [DETERMINE_dia_endo_AVratios ; MESA_dia_endo_AVratios ];
trainingdata(:,18) = [DETERMINE_sys_endo_AVratios ; MESA_sys_endo_AVratios ];
trainingdata(:,19) = [DETERMINE_dia_epi_AVratios ; MESA_dia_epi_AVratios ];
trainingdata(:,20) = [DETERMINE_sys_epi_AVratios ; MESA_sys_epi_AVratios ];
% mean thickness
trainingdata(:,21) = [diaMeanT(data(1).DETERMINE_indices)' ; diaMeanT(data(1).MESA_indices)'];
trainingdata(:,22) = [sysMeanT(data(1).DETERMINE_indices)' ; sysMeanT(data(1).MESA_indices)'];
% mean(sys thickness) - mean(dia thickness) e.g. change in mean thickness from diastole to systole
trainingdata(:,23) = [deltaMeanT(data(1).DETERMINE_indices)' ; deltaMeanT(data(1).MESA_indices)'];
%most common thickness
trainingdata(:,24) = [diaModeT(data(1).DETERMINE_indices)' ; diaModeT(data(1).MESA_indices)'];
trainingdata(:,25) = [sysModeT(data(1).DETERMINE_indices)' ; sysModeT(data(1).MESA_indices)'];
% median thickness
trainingdata(:,26) = [diaMedianT(data(1).DETERMINE_indices)' ; diaMedianT(data(1).MESA_indices)'];
trainingdata(:,27) = [sysMedianT(data(1).DETERMINE_indices)' ; sysMedianT(data(1).MESA_indices)'];
%thickness variance for diastole and systole seperately
trainingdata(:,28) = [DETERMINEdiaMyoThicknessVariance' ; MESAdiaMyoThicknessVariance' ];
trainingdata(:,29) = [DETERMINEsysMyoThicknessVariance' ; MESAsysMyoThicknessVariance' ];
% var(sys thickness - dia thickness)  e.g. variance in the difference between diastole and systole
trainingdata(:,30) = [DETERMINEmyoTchangesVar' ;MESAmyoTchangesVar'];
% var([ dia thickness ; sys thickness])
 trainingdata(:,31) = [DETERMINE_DiaSys_dEPI2ENDO_vars' ; MESA_DiaSys_dEPI2ENDO_vars' ];
%variance of the thickness in each of the 3 different sections
trainingdata(:,32) = [cell2mat({data(data(1).DETERMINE_indices).dia_vA_var})'  ; cell2mat({data(data(1).MESA_indices).dia_vA_var})'];
trainingdata(:,33) = [cell2mat({data(data(1).DETERMINE_indices).dia_vB_var})'  ; cell2mat({data(data(1).MESA_indices).dia_vB_var})'];
trainingdata(:,34) = [cell2mat({data(data(1).DETERMINE_indices).dia_vC_var})'  ; cell2mat({data(data(1).MESA_indices).dia_vC_var})'];
trainingdata(:,35) = [cell2mat({data(data(1).DETERMINE_indices).sys_vA_var})'  ; cell2mat({data(data(1).MESA_indices).sys_vA_var})'];
trainingdata(:,36) = [cell2mat({data(data(1).DETERMINE_indices).sys_vB_var})'  ; cell2mat({data(data(1).MESA_indices).sys_vB_var})'];
trainingdata(:,37) = [cell2mat({data(data(1).DETERMINE_indices).sys_vC_var})'  ; cell2mat({data(data(1).MESA_indices).sys_vC_var})'];
trainingdata(:,38) = [cell2mat({data(data(1).DETERMINE_indices).dia_sys_vA_var})'  ; cell2mat({data(data(1).MESA_indices).dia_sys_vA_var})'];
trainingdata(:,39) = [cell2mat({data(data(1).DETERMINE_indices).dia_sys_vB_var})'  ; cell2mat({data(data(1).MESA_indices).dia_sys_vB_var})'];
trainingdata(:,40) = [cell2mat({data(data(1).DETERMINE_indices).dia_sys_vC_var})'  ; cell2mat({data(data(1).MESA_indices).dia_sys_vC_var})'];
%mean thickness for each of the 3 different sections
trainingdata(:,41) = [cell2mat({data(data(1).DETERMINE_indices).dia_vA_mean})'  ; cell2mat({data(data(1).MESA_indices).dia_vA_mean})'];
trainingdata(:,42) = [cell2mat({data(data(1).DETERMINE_indices).dia_vB_mean})'  ; cell2mat({data(data(1).MESA_indices).dia_vB_mean})'];
trainingdata(:,43) = [cell2mat({data(data(1).DETERMINE_indices).dia_vC_mean})'  ; cell2mat({data(data(1).MESA_indices).dia_vC_mean})'];
trainingdata(:,44) = [cell2mat({data(data(1).DETERMINE_indices).sys_vA_mean})'  ; cell2mat({data(data(1).MESA_indices).sys_vA_mean})'];
trainingdata(:,45) = [cell2mat({data(data(1).DETERMINE_indices).sys_vB_mean})'  ; cell2mat({data(data(1).MESA_indices).sys_vB_mean})'];
trainingdata(:,46) = [cell2mat({data(data(1).DETERMINE_indices).sys_vC_mean})'  ; cell2mat({data(data(1).MESA_indices).sys_vC_mean})'];
trainingdata(:,47) = [cell2mat({data(data(1).DETERMINE_indices).dia_sys_vA_mean})'  ; cell2mat({data(data(1).MESA_indices).dia_sys_vA_mean})'];
trainingdata(:,48) = [cell2mat({data(data(1).DETERMINE_indices).dia_sys_vB_mean})'  ; cell2mat({data(data(1).MESA_indices).dia_sys_vB_mean})'];
trainingdata(:,49) = [cell2mat({data(data(1).DETERMINE_indices).dia_sys_vC_mean})'  ; cell2mat({data(data(1).MESA_indices).dia_sys_vC_mean})'];
trainingdata(:,50) = [sys_endo_volumes(data(1).DETERMINE_indices) ; sys_endo_volumes(data(1).MESA_indices) ];
trainingdata(:,51) = [sys_epi_volumes(data(1).DETERMINE_indices) ; sys_epi_volumes(data(1).MESA_indices) ];
trainingdata(:,52) = [dia_endo_volumes(data(1).DETERMINE_indices) ; dia_endo_volumes(data(1).MESA_indices) ];
trainingdata(:,53) = [dia_epi_volumes(data(1).DETERMINE_indices) ; dia_epi_volumes(data(1).MESA_indices) ];
trainingdata(:,54) = [log(sys_endo_volumes(data(1).DETERMINE_indices)) ; log(sys_endo_volumes(data(1).MESA_indices)) ];
trainingdata(:,55) = [log(sys_epi_volumes(data(1).DETERMINE_indices)) ; log(sys_epi_volumes(data(1).MESA_indices)) ];
trainingdata(:,56) = [log(dia_endo_volumes(data(1).DETERMINE_indices)) ; log(dia_endo_volumes(data(1).MESA_indices)) ];
trainingdata(:,57) = [log(dia_epi_volumes(data(1).DETERMINE_indices)) ; log(dia_epi_volumes(data(1).MESA_indices)) ];
% sum(systole thickness)/sum(diastole thickness
% trainingdata(:,58) = [MyoThicknessSysDiaRatio(data(1).DETERMINE_indices)' ; MyoThicknessSysDiaRatio(data(1).MESA_indices)'];
trainingdata(:,58:72) = [DETERMINE_dia_sys_dEPI2ENDOs_b(:,1:15) ; MESA_dia_sys_dEPI2ENDOs_b(:,1:15)];

%% training data labels
trainingdataLabels = [
    'ejection fraction        ' ;...
%     'sys myo b1        ' ;...
%     'sys myo b2        ' ;...
%     'sys myo b3        ' ;...
%     'sys myo b4        ' ;...
%     'sys myo b5        ' ;...
%     'dia myo b1        ' ;...
%     'dia myo b2        ' ;...
%     'dia myo b3        ' ;...
%     'dia myo b4        ' ;...
%     'dia myo b5        ' ;...
    'dia sys myo b1           ' ;...
    'dia sys myo b2           ' ;...
    'dia sys myo b3           ' ;...
    'dia sys myo b4           ' ;...
    'dia sys myo b5           ' ;...
    'dia sys myo b6           ' ;...
    'dia sys myo b7           ' ;...
    'dia sys myo b8           ' ;...
    'dia sys myo b9           ' ;...
    'dia sys myo b10          ' ;...
    'dia sys myo b11          ' ;...
    'dia sys myo b12          ' ;...
    'dia sys shape mode 13    ' ;...
    'dia sys myo b14          ' ;...
    'dia sys myo b15          ' ;...
    'diaendo sphericity       ' ;...
    'sysendo sphericity       ' ;...
    'diaepi sphericity        ' ;...
    'sysepi sphericity        ' ;...
    'diaMeanT                 ' ;...
    'sysMeanT                 ' ;...
    'deltameanT               ' ;...
    'diaModeT                 ' ;...
    'sysModeT                 ' ;...
    'diaMedianT               ' ;...
    'sysMedianT               ' ;...
    'diaMyoThicknessVar       ' ;...
    'sysMyoThicknessVar       ' ;...
    'thickness change variance' ;...
    'DiaSysdEPI2ENDOvar       ' ;...
    'dia_vA_var               ' ;...
    'dia_vB_var               ' ;...
    'dia_vC_var               ' ;...
    'sys_vA_var               ' ;...
    'sys_vB_var               ' ;...
    'sys_vC_var               ' ;...
    'dia_sys_vA_var           ' ;...
    'dia_sys_vB_var           ' ;...
    'dia_sys_vC_var           ' ;...
    'dia_vA_mean              ' ;...
    'dia_vB_mean              ' ;...
    'dia_vC_mean              ' ;...
    'sys_vA_mean              ' ;...
    'sys_vB_mean              ' ;...
    'sys_vC_mean              ' ;...
    'dia_sys_vA_mean          ' ;...
    'dia_sys_vB_mean          ' ;...
    'dia_sys_vC_mean          ' ;...
    'sys endo volume          ' ;...
    'sys epi volume           ' ;...
    'dia endo volume          ' ;...%62
    'dia epi volume           ' ;...%63
    'log sys endo volume      ' ;...%64
    'log sys epi volume       ' ;...%65
    'log dia endo volume      ' ;...%66
    'log dia epi volume       ' ;...%67
%     'sum(sysT)/sum(diaT' ;...
    'dia sys T b1             ' ;...
    'dia sys T b2             ' ;...
    'dia sys T b3             ' ;...
    'dia sys T b4             ' ;...
    'dia sys T b5             ' ;...
    'dia sys T b6             ' ;...
    'dia sys thickness mode 7 ' ;...
    'dia sys T b8             ' ;...
    'dia sys T b9             ' ;...
    'dia sys T b10            ' ;...
    'dia sys T b11            ' ;...
    'dia sys T b12            ' ;...
    'dia sys T b13            ' ;...
    'dia sys T b14            ' ;...
    'dia sys T b15            '] ;%72
    
    
    

%% class names
names = char(200,1);
names(1:100,1) = 'd';
names(101:200,1) = 'm';