TESTdata = zeros(200,83);

TESTdata(:,1) = [TEST_ejectionFractions'];
%modes of variation
TESTdata(:,2:6) = [TEST_sys_myo_b(:,1:5) ]; %from the PDM
TESTdata(:,7:11) = [TEST_dia_myo_b(:,1:5) ];
TESTdata(:,12:26) = [TEST_dia_sys_myo_b(:,1:15) ];
%sphericity measure
TESTdata(:,27) = [TEST_dia_endo_AVratios ];
TESTdata(:,28) = [TEST_sys_endo_AVratios ];
TESTdata(:,29) = [TEST_dia_epi_AVratios ];
TESTdata(:,30) = [TEST_sys_epi_AVratios ];
% mean thickness
TESTdata(:,31) = [diaMeanT(data(1).TEST_indices)'];
TESTdata(:,32) = [sysMeanT(data(1).TEST_indices)' ];
% mean(sys thickness) - mean(dia thickness) e.g. change in mean thickness from diastole to systole
TESTdata(:,33) = [deltaMeanT(data(1).TEST_indices)' ];
%most common thickness];
TESTdata(:,35) = [sysModeT(data(1).TEST_indices)' ];
% median thickness
TESTdata(:,36) = [diaMedianT(data(1).TEST_indices)' ];
TESTdata(:,37) = [sysMedianT(data(1).TEST_indices)' ];
%thickness variance for diastole and systole seperately
TESTdata(:,38) = [TESTdiaMyoThicknessVariance'  ];
TESTdata(:,39) = [TESTsysMyoThicknessVariance'  ];
% var(sys thickness - dia thickness)  e.g. variance in the difference between diastole and systole
TESTdata(:,40) = [TESTmyoTchangesVar' ];
% var([ dia thickness ; sys thickness])
 TESTdata(:,41) = [TEST_DiaSys_dEPI2ENDO_vars' ];
%variance of the thickness in each of the 3 different sections
TESTdata(:,42) = [cell2mat({data(data(1).TEST_indices).dia_vA_var})'  ];
TESTdata(:,43) = [cell2mat({data(data(1).TEST_indices).dia_vB_var})'  ];
TESTdata(:,44) = [cell2mat({data(data(1).TEST_indices).dia_vC_var})'  ];
TESTdata(:,45) = [cell2mat({data(data(1).TEST_indices).sys_vA_var})'  ];
TESTdata(:,46) = [cell2mat({data(data(1).TEST_indices).sys_vB_var})'  ];
TESTdata(:,47) = [cell2mat({data(data(1).TEST_indices).sys_vC_var})'  ];
TESTdata(:,48) = [cell2mat({data(data(1).TEST_indices).dia_sys_vA_var})' ];
TESTdata(:,49) = [cell2mat({data(data(1).TEST_indices).dia_sys_vB_var})' ];
TESTdata(:,50) = [cell2mat({data(data(1).TEST_indices).dia_sys_vC_var})' ];
%mean thickness for each of the 3 different sections
TESTdata(:,51) = [cell2mat({data(data(1).TEST_indices).dia_vA_mean})'  ];
TESTdata(:,52) = [cell2mat({data(data(1).TEST_indices).dia_vB_mean})'  ];
TESTdata(:,53) = [cell2mat({data(data(1).TEST_indices).dia_vC_mean})'  ];
TESTdata(:,54) = [cell2mat({data(data(1).TEST_indices).sys_vA_mean})'  ];
TESTdata(:,55) = [cell2mat({data(data(1).TEST_indices).sys_vB_mean})' ];
TESTdata(:,56) = [cell2mat({data(data(1).TEST_indices).sys_vC_mean})' ];
TESTdata(:,57) = [cell2mat({data(data(1).TEST_indices).dia_sys_vA_mean})'  ];
TESTdata(:,58) = [cell2mat({data(data(1).TEST_indices).dia_sys_vB_mean})'  ];
TESTdata(:,59) = [cell2mat({data(data(1).TEST_indices).dia_sys_vC_mean})' ];
TESTdata(:,60) = [sys_endo_volumes(data(1).TEST_indices) ];
TESTdata(:,61) = [sys_epi_volumes(data(1).TEST_indices)  ];
TESTdata(:,62) = [dia_endo_volumes(data(1).TEST_indices) ];
TESTdata(:,63) = [dia_epi_volumes(data(1).TEST_indices) ];
TESTdata(:,64) = [log(sys_endo_volumes(data(1).TEST_indices)) ];
TESTdata(:,65) = [log(sys_epi_volumes(data(1).TEST_indices)) ];
TESTdata(:,66) = [log(dia_endo_volumes(data(1).TEST_indices)) ];
TESTdata(:,67) = [log(dia_epi_volumes(data(1).TEST_indices)) ];
% sum(systole thickness)/sum(diastole thickness
TESTdata(:,68) = [MyoThicknessSysDiaRatio(data(1).TEST_indices)' ];
TESTdata(:,69:83) = [TEST_dia_sys_dEPI2ENDOs_b(:,1:15) ];
%% training data labels
TESTdataLabels = [
    'EF                ' ;...
    'sys myo b1        ' ;...
    'sys myo b2        ' ;...
    'sys myo b3        ' ;...
    'sys myo b4        ' ;...
    'sys myo b5        ' ;...
    'dia myo b1        ' ;...
    'dia myo b2        ' ;...
    'dia myo b3        ' ;...
    'dia myo b4        ' ;...
    'dia myo b5        ' ;...
    'dia sys myo b1    ' ;...
    'dia sys myo b2    ' ;...
    'dia sys myo b3    ' ;...
    'dia sys myo b4    ' ;...
    'dia sys myo b5    ' ;...
    'dia sys myo b6    ' ;...
    'dia sys myo b7    ' ;...
    'dia sys myo b8    ' ;...
    'dia sys myo b9    ' ;...
    'dia sys myo b10   ' ;...
    'dia sys myo b11   ' ;...
    'dia sys myo b12   ' ;...
    'dia sys myo b13   ' ;...
    'dia sys myo b14   ' ;...
    'dia sys myo b15   ' ;...
    'diaendo sphericity' ;...
    'sysendo sphericity' ;...
    'diaepi sphericity ' ;...
    'sysepi sphericity ' ;...
    'diaMeanT          ' ;...
    'sysMeanT          ' ;...
    'deltameanT        ' ;...
    'diaModeT          ' ;...
    'sysModeT          ' ;...
    'diaMedianT        ' ;...
    'sysMedianT        ' ;...
    'diaMyoThicknessVar' ;...
    'sysMyoThicknessVar' ;...
    'myoTchangesVar    ' ;...
    'DiaSysdEPI2ENDOvar' ;...
    'dia_vA_var        ' ;...
    'dia_vB_var        ' ;...
    'dia_vC_var        ' ;...
    'sys_vA_var        ' ;...
    'sys_vB_var        ' ;...
    'sys_vC_var        ' ;...
    'dia_sys_vA_var    ' ;...
    'dia_sys_vB_var    ' ;...
    'dia_sys_vC_var    ' ;...
    'dia_vA_mean       ' ;...
    'dia_vB_mean       ' ;...
    'dia_vC_mean       ' ;...
    'sys_vA_mean       ' ;...
    'sys_vB_mean       ' ;...
    'sys_vC_mean       ' ;...
    'dia_sys_vA_mean   ' ;...
    'dia_sys_vB_mean   ' ;...
    'dia_sys_vC_mean   ' ;...
    'sys endo volume   ' ;...
    'sys epi volume    ' ;...
    'dia endo volume   ' ;...%62
    'dia epi volume    ' ;...%63
    'log sys endo vol  ' ;...%64
    'log sys epi vol   ' ;...%65
    'log dia endo vol  ' ;...%66
    'log dia epi vol   ' ;...%67
    'sum(sysT)/sum(diaT' ;...
    'dia sys T b1      ' ;...
    'dia sys T b2      ' ;...
    'dia sys T b3      ' ;...
    'dia sys T b4      ' ;...
    'dia sys T b5      ' ;...
    'dia sys T b6      ' ;...
    'dia sys T b7      ' ;...
    'dia sys T b8      ' ;...
    'dia sys T b9      ' ;...
    'dia sys T b10     ' ;...
    'dia sys T b11     ' ;...
    'dia sys T b12     ' ;...
    'dia sys T b13     ' ;...
    'dia sys T b14     ' ;...
    'dia sys T b15     '] ;%83
    